version: '3'

services:
  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key_here
      - SUPERSET_LOAD_EXAMPLES=no
    volumes:
      - superset_home:/app/superset_home
    depends_on:
      - superset_init
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  superset_init:
    image: apache/superset:latest
    container_name: superset_init
    command: |
      bash -c '
      superset db upgrade &&
      superset fab create-admin \
        --username admin \
        --firstname Superset \
        --lastname Admin \
        --email admin@superset.com \
        --password admin &&
      superset init
      '
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key_here
    depends_on:
      - db_dwh

volumes:
  superset_home: 