x-postgres-common: &postgres-common
  image: postgres:14-alpine
  user: postgres
  restart: always
  healthcheck:
    test: 'pg_isready -U admin --dbname=airline_tickets'
    interval: 10s
    timeout: 5s
    retries: 5

services:
  db_primary:
    <<: *postgres-common
    container_name: postgres_primary
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: airline_tickets
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    command: |
      postgres 
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c hot_standby=on
      -c hot_standby_feedback=on
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/00_init.sql
      - ./schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./create_views.sql:/docker-entrypoint-initdb.d/02_create_views.sql

  db_replica:
    <<: *postgres-common
    container_name: postgres_replica
    ports:
      - "5433:5432"
    environment:
      PGUSER: replicator
      PGPASSWORD: replicator_password
    command: |
      bash -c "
      until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot --host=db_primary --port=5432
      do
      echo 'Waiting for primary to connect...'
      sleep 1s
      done
      echo 'Backup done, starting replica...'
      chmod 0700 /var/lib/postgresql/data
      postgres
      "
    depends_on:
      - db_primary
    volumes:
      - postgres_replica_data:/var/lib/postgresql/data

  db_dwh:
    <<: *postgres-common
    container_name: postgres_dwh
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: airline_tickets_dwh
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - postgres_dwh_data:/var/lib/postgresql/data
      - ./dwh_schema.sql:/docker-entrypoint-initdb.d/01_dwh_schema.sql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9092 --list
      interval: 30s
      timeout: 10s
      retries: 3

  debezium:
    image: debezium/connect:2.3
    container_name: debezium
    depends_on:
      kafka:
        condition: service_healthy
      db_primary:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      OFFSET_FLUSH_INTERVAL_MS: 10000

  dmp_service:
    build:
      context: .
      dockerfile: Dockerfile.dmp
    container_name: dmp_service
    depends_on:
      - kafka
      - db_dwh
      - debezium
    restart: always
    environment:
      PYTHONUNBUFFERED: 1

  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key_here
      - SUPERSET_LOAD_EXAMPLES=no
      - POSTGRES_DB=airline_tickets_dwh
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_HOST=db_dwh
      - POSTGRES_PORT=5432
    volumes:
      - superset_home:/app/superset_home
    depends_on:
      - superset_init
      - db_dwh
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  superset_init:
    image: apache/superset:latest
    container_name: superset_init
    depends_on:
      - db_dwh
    command: |
      bash -c '
      superset db upgrade &&
      superset fab create-admin \
        --username admin \
        --firstname Superset \
        --lastname Admin \
        --email admin@superset.com \
        --password admin &&
      superset init
      '
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key_here
      - POSTGRES_DB=airline_tickets_dwh
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_HOST=db_dwh
      - POSTGRES_PORT=5432

volumes:
  postgres_primary_data:
  postgres_replica_data:
  postgres_dwh_data:
  superset_home: